### ISSUE TITLE
Exeception Tried to Register two view with same name RNGestureHandlerButton

### ISSUE THREAD

**Issue by sk1794** [thomas-coldwell/expo-image-editor#22]
![image](https://user-images.githubusercontent.com/30054578/103483279-21e28700-4e0c-11eb-85f9-d01dd23ea21f.png)
![image](https://user-images.githubusercontent.com/30054578/103483287-2d35b280-4e0c-11eb-86e1-72729cf20c66.png)

I am getting two error in module and an exption, i have attached error log

**Comment by sanbat** [comment]
@sk1794 this package using "react-native-gesture-handler": "^1.8.0" so your app should use same version of "react-native-gesture-handler". Please check your app package.json and verify the version of "react-native-gesture-handler".

So that you can eradicate this error.

**Comment by thomas-coldwell** [comment]
Closed as part of #36
