### ISSUE TITLE
Need an option to describe which editing features to apply. 

### ISSUE THREAD

**Issue by RohitKaushal7** [thomas-coldwell/expo-image-editor#23]
I just want user to crop image in a specified aspect ratio. but not be able to blur the image. need support for that.

**Comment by thomas-coldwell** [comment]
There's a couple of options that I've been thinking about for this.

The first would be to have a prop to specify which transformation and image adjustment tools (e.g. an array of `transformationOptions`) are shown and the user is allowed to use and keep the UI basically the same as it is at the minute, just conditionally rendering the buttons for each.

Alternatively, a different prop could be used to set predefined UI modes e.g. `crop-only`, `blur-only`.

I think the first one is probably much more flexible and makes it easier to add other transformation and image adjustment options in the future.

**Comment by RohitKaushal7** [comment]
yes the first one seems flexible.. also if possible allow a prop like `defaultMode` or something which takes user to the specific editor screen..
the use case is like if some app wants user to necessarily crop an image to some aspect ratio so user should be automatically on the crop screen otherwise they won't know what to do.

**Comment by thomas-coldwell** [comment]
Yeah I think having it so it forces the user into only allowing them to crop the image is a really good use case for profile pictures etc. where you want the user to select and crop it square and not be able to apply any other transformations or adjustments.

Thanks for the feedback - will try get this followed up within the next week!
