### ISSUE TITLE
Not able to move crop overlay on Android devices.

### ISSUE THREAD

**Issue by giriprabu** [thomas-coldwell/expo-image-editor#41]
It is not possible to move or change the size of the crop overlay on Android devices. I tested this on Samsung s20FE and Pixel 3a both running Android 11. Can you please check this issue on your side? The editor is working fine on iOS devices.

**Comment by mmelilli** [comment]
I confirm it doesn't work in android 11 (i'm testing in a Pixel 3a too)

**Comment by Svarto** [comment]
Same problem here, anyone found a fix?

**Comment by giriprabu** [comment]
I forked the expo-image-editor library and changed the library code to fix the issue. I then installed the library directly from the forked git rather than from npm. Hope this helps.

**Comment by thomas-coldwell** [comment]
Hey folks sorry for the inactivity! This should be fixes in the latest release v1.6.0 now - a bit of a workaround was required - it was an issue with React Navigation and the use of the `GestureHandlerRootView` we use in the modal - full issue can be read here https://github.com/react-navigation/react-navigation/issues/9757.

In the meantime you will need to import the `<ImageEditorView />` component from the library and then place that in a Stack Modal as per the React Navigation docs https://reactnavigation.org/docs/modal/

Hope this helps :)

**Comment by thomas-coldwell** [comment]
I've updated the docs to reflect this - you can now use it as a regular view (with no modal) using the `asView` prop. Then you can render this view in whatever you would like e.g. React Native Modal or React Navigation Stack Modal - the latter which will solve the issue you were facing on Android as per my last comment. Hope this helps!

**Comment by e-hosseini** [comment]
@thomas-coldwell It seems the solution is not working if you put the ImageEditor inside the Modal! Without modal in a normal View it works fine.
